language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

before_install:
  - composer self-update --no-interaction

install:
  - composer install --dev --prefer-source --no-interaction

script: ./bin/phpspec run --format=pretty
